### ISSUE TITLE
"buf must be a byte string"

### ISSUE THREAD

**Issue by Makabra** [bboe/reddit_irc#3]
Hi, I'm pretty new with python Idk what I'm doing wrong

Traceback (most recent call last):
  File "/usr/local/bin/reddit_irc", line 9, in <module>
    load_entry_point('reddit-irc==0.1.3', 'console_scripts', 'reddit_irc')()
  File "build/bdist.linux-x86_64/egg/reddit_irc.py", line 158, in main
  File "build/bdist.linux-x86_64/egg/reddit_irc.py", line 106, in __init__
  File "build/bdist.linux-x86_64/egg/reddit_irc.py", line 117, in load_configuration
  File "build/bdist.linux-x86_64/egg/reddit_irc.py", line 133, in parse_server
  File "build/bdist.linux-x86_64/egg/reddit_irc.py", line 71, in __init__
  File "/usr/local/lib/python2.7/dist-packages/praw-3.4.0-py2.7.egg/praw/__init__.py", line 565, in get_content
    page_data = self.request_json(url, params=params)
  File "<decorator-gen-8>", line 2, in request_json
  File "/usr/local/lib/python2.7/dist-packages/praw-3.4.0-py2.7.egg/praw/decorators.py", line 116, in raise_api_exceptions
    return_value = function(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/praw-3.4.0-py2.7.egg/praw/__init__.py", line 620, in request_json
    retry_on_error=retry_on_error)
  File "/usr/local/lib/python2.7/dist-packages/praw-3.4.0-py2.7.egg/praw/__init__.py", line 451, in _request
    response = handle_redirect()
  File "/usr/local/lib/python2.7/dist-packages/praw-3.4.0-py2.7.egg/praw/__init__.py", line 432, in handle_redirect
    verify=self.http.validate_certs, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/praw-3.4.0-py2.7.egg/praw/handlers.py", line 146, in wrapped
    result = function(cls, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/praw-3.4.0-py2.7.egg/praw/handlers.py", line 56, in wrapped
    return function(cls, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/praw-3.4.0-py2.7.egg/praw/handlers.py", line 102, in request
    allow_redirects=False, verify=verify)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 569, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 362, in send
    timeout=timeout
  File "/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 516, in urlopen
    body=body, headers=headers)
  File "/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 308, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python2.7/httplib.py", line 1001, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1035, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 997, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 850, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 826, in send
    self.sock.sendall(data)
  File "/usr/lib/python2.7/dist-packages/urllib3/contrib/pyopenssl.py", line 208, in sendall
    return self.connection.sendall(data)
  File "/usr/lib/python2.7/dist-packages/OpenSSL/SSL.py", line 969, in sendall
    raise TypeError("buf must be a byte string")
TypeError: buf must be a byte string

**Comment by nelsonjchen** [comment]
This looks related to this:

https://github.com/pyca/pyopenssl/issues/15

**Comment by bboe** [comment]
Is someone interested in looking into resolving this issue? I don't use this tool any more so have little desire to look into potential bug fixes.

**Comment by Makabra** [comment]
It looks like the problem is pyopenssl, I'll close the issue 'cus isn't a bug of the bot, thanks for the answer!
